services:
  inventory-service:
    build: ./inventory-service
    ports:
      - "8081:8081"
  order-service:
    build: ./order-service
    environment:
      INVENTORY_BASE_URL: "http://inventory-service:8081"
    ports:
      - "8080:8080"
    depends_on:
      - inventory-service
