server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:inventorydb;DB_CLOSE_DELAY=-1;MODE=LEGACY
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true

# Seed data
